default:
  image: mcr.microsoft.com/dotnet/core/sdk:3.0

Build:
  stage: build
  script: 
    - 'docker pull mcr.microsoft.com/dotnet/sdk:6.0'
    - 'dotnet restore src/PTABackEnd/PTABackEnd.sln'
    - 'dotnet build src/PTABackEnd/PTABackEnd.sln'    
  tags:
    - docker

Test:
  stage: test
  script: 
    - 'dotnet test src/PTABackEnd/PTABackEnd.sln --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths: 
     - ./**/*test-result.xml
    reports:
      junit: 
       - ./**/*test-result.xml
