name: Run Unit Tests
on:
  push:
    branches:
    - feature/*
  workflow_dispatch:
    
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  APP_WORKING_DIRECTORY: src/PokemonTabletopAdventures.CoreApi
  TEST_WORKING_DIRECTORY: src/PokemonTabletopAdventures.CoreApi.UnitTests
  AZURE_WEBAPP_NAME: pta-2
  AZURE_WEBAPP_PACKAGE_PATH: PokemonTabletopAdventures.CoreApi\published
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Add Source
      run: dotnet nuget add source --username cstewart2010 --password ${{ secrets.DEPLOY_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/cstewart2010/index.json"
    - name: Restore Unit Tests
      run: dotnet restore "${{ env.TEST_WORKING_DIRECTORY }}"
    - name: Build Unit Tests
      run: dotnet build "${{ env.TEST_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Run Unit Tests
      run: dotnet test "${{ env.TEST_WORKING_DIRECTORY }}" --collect:"Xplat Code Coverage"
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: '${{ env.TEST_WORKING_DIRECTORY }}/TestResults/*/coverage.cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'both'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
    - name: Publish
      run: dotnet publish "${{ env.APP_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
